---
title: "IATI Visualisation"
output: html_document
editor_options: 
  chunk_output_type: console
---

<!-- Run this 'development' chunk -->
<!-- Store every call to library() that you need to explore your functions -->

```{r development, include=FALSE}
library(testthat)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.

If it is the first time you use {fusen}, after 'description', you can directly run the last chunk of the present file with inflate() inside.
--> 


# Show donors 

<!--
Create a chunk for the core of the function

- The chunk needs to be named `function` at least
- It contains the code of a documented function
- The chunk can also be named `function-show_donors` to make it easily
findable in your Rmd
- Let the `@examples` part empty, and use the next `examples` chunk instead

After inflating the template

-  This function code will be added in a new file in the "R/" directory
-->

```{r function-show_donors, echo=FALSE, message=FALSE, warning=FALSE}
#' Ploting Donors
#'
#' 
#' @param year year to select starting from 2016 - could be one year or a list
#' @param geo Region or Country or Site
#' @param transtype Transaction type
#' 
#' @inheritParams ggplot2::ggplot
#'
#' @export
#'
#' @examples
show_donors <- function(year, 
                        geo,
                        transtype  ) {
  #require(ggplot2)
  require(tidyverse)
  require(scales)
p<- iati::transaction %>%
  dplyr::left_join(iati::codeOrganisationType %>%
                     dplyr::mutate(transorg_type = name) %>%
                     dplyr::select(code, transorg_type) ,
                   by= c("transaction_provider_org_type" = "code")) %>%
  dplyr::left_join(iati::codeTransactionType %>%
                     dplyr::mutate(TransactionType = name,
                                   TransactionDescr = description) %>%
                     dplyr::select(code, TransactionType,TransactionDescr  ) ,
                   by= c("transaction_type_code" = "code")) %>%
  dplyr::left_join(iati::codeAidTypeVocabulary %>%
                     dplyr::mutate(aidvocabulary1 = name,
                                   aidvocabularyDescr1 = description) %>%
                     dplyr::select(code, aidvocabulary1,aidvocabularyDescr1  ) ,
                   by= c("transaction_aid_type_vocabulary_1" = "code")) %>%
  dplyr::left_join(iati::codeAidType %>%
                     dplyr::mutate(AidType1 = name,
                                   AidTypeDescr1 = description) %>%
                     dplyr::select(code, AidType1,AidTypeDescr1  ) ,
                   by= c("transaction_aid_type_code_1" = "code")) %>%
  dplyr::left_join(iati::codeAidTypeVocabulary %>%
                     dplyr::mutate(aidvocabulary2 = name,
                                   aidvocabularyDescr2 = description) %>%
                     dplyr::select(code, aidvocabulary2,aidvocabularyDescr2  ) ,
                   by= c("transaction_aid_type_vocabulary_2" = "code"))%>%
  dplyr::left_join(iati::codeAidType %>%
                     dplyr::mutate(AidType2 = name,
                                   AidTypeDescr2 = description) %>%
                     dplyr::select(code, AidType2,AidTypeDescr2  ) ,
                   by= c("transaction_aid_type_code_2" = "code")) %>%
  
  dplyr::left_join(iati::activity %>%
                     dplyr::left_join(iati::codeOrganisationType %>%
                                        dplyr::mutate(report_org_type = name) %>%
                                        dplyr::select(code, report_org_type) ,
                                      by= c("reporting_org_type" = "code")) %>%
                     dplyr::left_join(iati::codeActivityScope %>%
                                        dplyr::mutate(codeActivityScope = name) %>%
                                        dplyr::select(code, codeActivityScope) ,
                                      by= c("activity_scope_code" = "code"))  %>%
                     dplyr::left_join(iati::codeCountry %>%
                                        dplyr::mutate(recipientCountry = name) %>%
                                        dplyr::select(code, recipientCountry) ,
                                      by= c("recipient_country_code" = "code")) %>%
                     dplyr::left_join(iati::codeRegion %>%
                                        dplyr::mutate(recipientRegion = name) %>%
                                        dplyr::select(code, recipientRegion) ,
                                      by= c("recipient_region_code" = "code")) %>%
                     
                     dplyr::left_join(iati::codeActivityStatus %>%
                                        dplyr::mutate(ActivityStatus = name) %>%
                                        dplyr::select(code, ActivityStatus) ,
                                      by= c("activity_status_code" = "code")) %>%
                     dplyr::left_join(iati::codeCollaborationType %>%
                                        dplyr::mutate(CollaborationType = name) %>%
                                        dplyr::select(code, CollaborationType) ,
                                      by= c("collaboration_type_code" = "code"))  ,
                   by= c("iati_identifier")) %>%
  
  ## Add filters 
  dplyr::filter(transaction_type_code == transtype, ## Add filters transaction type 
                lubridate::year(transaction_date) >= year  ## Add filters transaction type 
                ) %>%
  
  dplyr::mutate(
    trans_year = lubridate::year(transaction_date),
    month_trans = factor(format(transaction_date, "%b"), month.abb, ordered = TRUE)
  ) %>%
  dplyr::select(trans_year, month_trans, transaction_value) %>%
#  dplyr::filter(transaction_value <= 1000000 & transaction_value > 1000) %>%
  ggplot2::ggplot(aes(y = transaction_value,
             x = month_trans )) +
  geom_bar(alpha = 0.9, stat = "identity") +
#  scale_x_continuous(labels = scales::label_number(scale_cut = cut_short_scale())) +
  facet_wrap(~ trans_year) +
  #theme_minimal() +
  #unhcRstyle::unhcr_theme() +
  labs(
    title = "Donations received by UNHCR",
    subtitle = "Between 2014 and 2022",
    x = "",
    y = "",
    caption = "IATI Package - github.com/unhcr-americas/iati"
  ) 
  p
}
```

<!--
Create a chunk with an example of use for your function

- The chunk needs to be named `examples` at least
- It contains working examples of your function
- The chunk is better be named `examples-show_donors` to be handled
correctly when inflated as a vignette

After inflating the template

-  This example will be added in the '@examples' part of our function above in the "R/" directory
- This example will be added in the vignette created from this Rmd template
-->

```{r examples-show_donors, message=FALSE, warning=FALSE}
show_donors(year = 2020,
            geo = "The Americas",
            transtype = "11" )
# ,  ## "3"  "4"  "11"           metric = "USD"
```

<!--
Create a chunk with a test of use for your function

- The chunk needs to be named `tests` at least
- It contains working tests of your function
- The chunk is better be named `tests-show_donors` to be handled
correctly when inflated as a vignette

After inflating the template

-  This test code will be added in the "tests/testthat/" directory


 tests-show_donors,echo=FALSE,  message=FALSE, warning=FALSE}
# test_that("is_testing_possible", {
# 
# })
```-->



 

# Show implementers 

```{r function-show_implementers, echo=FALSE, message=FALSE, warning=FALSE}
#' Ploting implementers
#'
#' 
#' @param year year to select starting from 2016 - could be one year or a list
#' @param geo Region or Country or Site
#' @param transtype Transaction type
#' 
#' @inheritParams ggplot2::ggplot
#'
#' @export
#'
#' @examples
show_implementers <- function(year, 
                        geo,
                        transtype  ) {
  #require(ggplot2)
  require(tidyverse)
  require(scales)
p<- iati::transaction %>%
  dplyr::left_join(iati::codeOrganisationType %>%
                     dplyr::mutate(transorg_type = name) %>%
                     dplyr::select(code, transorg_type) ,
                   by= c("transaction_provider_org_type" = "code")) %>%
  dplyr::left_join(iati::codeTransactionType %>%
                     dplyr::mutate(TransactionType = name,
                                   TransactionDescr = description) %>%
                     dplyr::select(code, TransactionType,TransactionDescr  ) ,
                   by= c("transaction_type_code" = "code")) %>%
  dplyr::left_join(iati::codeAidTypeVocabulary %>%
                     dplyr::mutate(aidvocabulary1 = name,
                                   aidvocabularyDescr1 = description) %>%
                     dplyr::select(code, aidvocabulary1,aidvocabularyDescr1  ) ,
                   by= c("transaction_aid_type_vocabulary_1" = "code")) %>%
  dplyr::left_join(iati::codeAidType %>%
                     dplyr::mutate(AidType1 = name,
                                   AidTypeDescr1 = description) %>%
                     dplyr::select(code, AidType1,AidTypeDescr1  ) ,
                   by= c("transaction_aid_type_code_1" = "code")) %>%
  dplyr::left_join(iati::codeAidTypeVocabulary %>%
                     dplyr::mutate(aidvocabulary2 = name,
                                   aidvocabularyDescr2 = description) %>%
                     dplyr::select(code, aidvocabulary2,aidvocabularyDescr2  ) ,
                   by= c("transaction_aid_type_vocabulary_2" = "code"))%>%
  dplyr::left_join(iati::codeAidType %>%
                     dplyr::mutate(AidType2 = name,
                                   AidTypeDescr2 = description) %>%
                     dplyr::select(code, AidType2,AidTypeDescr2  ) ,
                   by= c("transaction_aid_type_code_2" = "code")) %>%
  
  dplyr::left_join(iati::activity %>%
                     dplyr::left_join(iati::codeOrganisationType %>%
                                        dplyr::mutate(report_org_type = name) %>%
                                        dplyr::select(code, report_org_type) ,
                                      by= c("reporting_org_type" = "code")) %>%
                     dplyr::left_join(iati::codeActivityScope %>%
                                        dplyr::mutate(codeActivityScope = name) %>%
                                        dplyr::select(code, codeActivityScope) ,
                                      by= c("activity_scope_code" = "code"))  %>%
                     dplyr::left_join(iati::codeCountry %>%
                                        dplyr::mutate(recipientCountry = name) %>%
                                        dplyr::select(code, recipientCountry) ,
                                      by= c("recipient_country_code" = "code")) %>%
                     dplyr::left_join(iati::codeRegion %>%
                                        dplyr::mutate(recipientRegion = name) %>%
                                        dplyr::select(code, recipientRegion) ,
                                      by= c("recipient_region_code" = "code")) %>%
                     
                     dplyr::left_join(iati::codeActivityStatus %>%
                                        dplyr::mutate(ActivityStatus = name) %>%
                                        dplyr::select(code, ActivityStatus) ,
                                      by= c("activity_status_code" = "code")) %>%
                     dplyr::left_join(iati::codeCollaborationType %>%
                                        dplyr::mutate(CollaborationType = name) %>%
                                        dplyr::select(code, CollaborationType) ,
                                      by= c("collaboration_type_code" = "code"))  ,
                   by= c("iati_identifier")) %>%
  
  ## Add filters 
  dplyr::filter(transaction_type_code == transtype, ## Add filters transaction type 
                lubridate::year(transaction_date) >= year  ## Add filters transaction type 
                ) %>%
  
  dplyr::mutate(
    trans_year = lubridate::year(transaction_date),
    month_trans = factor(format(transaction_date, "%b"), month.abb, ordered = TRUE)
  ) %>%
  dplyr::select(trans_year, month_trans, transaction_value) %>%
#  dplyr::filter(transaction_value <= 1000000 & transaction_value > 1000) %>%
  ggplot2::ggplot(aes(y = transaction_value,
             x = month_trans )) +
  geom_bar(alpha = 0.9, stat = "identity") +
  #scale_x_continuous(labels = scales::label_number(scale_cut = cut_short_scale())) +
  facet_wrap(~ trans_year) +
  theme_minimal() +
 # unhcRstyle::unhcr_theme() +
  labs(
    title = "Donations received by UNHCR",
    subtitle = "Between 2014 and 2022",
    x = "",
    y = "",
    caption = "IATI Package - github.com/unhcr-americas/iati"
  ) 
  p
}
```
 
```{r examples-show_implementers, message=FALSE, warning=FALSE}
show_implementers(year = 2020,
            geo = "The Americas",
            transtype = "11" ) 
```







<!--
# There can be development actions

Create a chunk with 'development' actions

- The chunk needs to be named `development` or `dev`
- It contains functions that are used for package development only
- Note that you may want to store most of these functions in the 0-dev_history.Rmd file

These are only included in the present flat template file, their content will not be part of the package anywhere else.
-->


```{r developmenttest, include=FALSE, message=FALSE, warning=FALSE}
library(testthat)
# Load already included functions
pkgload::load_all(export_all = FALSE)
```


```{r development-inflate, eval=FALSE}
# Inflate the package

# You're one inflate from paper to box.
# Build your package from this very Rmd using `fusen::inflate()`
# 
# - Verify your `"DESCRIPTION"` file has been updated
# - Verify your function is in `"R/"` directory
# - Verify your test is in `"tests/testthat/"` directory
# - Verify this Rmd appears in `"vignettes/"` directory

# Keep eval=FALSE to avoid infinite loop in case you hit the knit button
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_full.Rmd", vignette_name = "Get started")
```



