# WARNING - Generated by {fusen} from dev/dev_unhcr_programme.Rmd: do not edit by hand

#' show_budget_gap
#' 
#' @param year A numeric value corresponding to the first year of focus until the most recent year within the dataset.
#' @param programme_lab A character vector corresponding to the name of the programme.
#' @param iati_identifier_ops A character vector corresponding to the name of the operation.
#' @param ctr_name A character vector corresponding to the name of the country.
#' 
#' @import ggplot2
#' @import dplyr
#' @import tidyselect
#' @import scales
#' @import unhcrthemes 
#'
#' @export 
#' @return  a graph
#' @examples
#' show_budget_gap(year = 2018, 
#'              ctr_name = "Brazil")
show_budget_gap <- function(year, 
                        programme_lab = NULL, 
                        iati_identifier_ops = NULL, 
                        ctr_name = NULL ) {
  
  
  # Check if only one argument is passed 
  if (!is.null(programme_lab) && !is.null(iati_identifier_ops)) {
    stop("Please pass only one of the arguments programme_lab or iati_identifier_ops.")
  } else if (!is.null(programme_lab) && !is.null(ctr_name)) {
    stop("Please pass only one of the arguments programme_lab or ctr_name.")
  } else if (!is.null(iati_identifier_ops) && !is.null(ctr_name)) {
    stop("Please pass only one of the arguments iati_identifier_ops or ctr_name.")
  }
  
  df <-  iati::dataTransaction |> 
         dplyr::left_join(iati::dataActivity, by= c("iati_identifier"))  
  
  if (!is.null(programme_lab)) {
    thisprogramme_lab <- programme_lab
    thisyear <-  year 
    df <- df |> 
      # levels(as.factor(df$programmme_lab))
      dplyr::filter( programmme_lab == thisprogramme_lab &
            year >= thisyear & 
             transaction_type_name ==  "Expenditure")
  } else if (!is.null(iati_identifier_ops)) {
    thisiati_identifier_ops <- iati_identifier_ops
    thisyear <-  year 
    df <- df |> 
      dplyr::filter(iati_identifier_ops == thisiati_identifier_ops &
            year >= thisyear & 
             transaction_type_name ==  "Expenditure")
  } else if (!is.null(ctr_name)) {
    thisctr_name <- ctr_name
    thisyear <-  year 
    df <- df |> 
      dplyr::filter( ctr_name == thisctr_name &
            year >= thisyear & 
             transaction_type_name ==  "Expenditure")
  }
  
   df2 <-  df  |> 
        dplyr::group_by(iati_identifier, year) |>
        dplyr::summarise(transaction_value= sum(transaction_value, na.rm = TRUE)) |>
        dplyr::left_join(iati::dataBudget |> 
                          dplyr::mutate(budget_value= as.numeric(budget_value)) |>
                          dplyr::group_by(iati_identifier) |>
                          dplyr::summarise(budget_value= sum(budget_value, na.rm = TRUE))  
                            , by= c("iati_identifier"))  |>
     dplyr::select(iati_identifier, year,budget_value,   transaction_value )  |>
     dplyr::mutate(budget_gap = (budget_value - transaction_value) / budget_value *100) 
   
 
 
 p <- df2 |> 
#  dplyr::filter(transaction_value_USD  <= 1000000 & transaction_value_USD  > 1000) |> 
  ggplot2::ggplot(ggplot2::aes(x =  year, group = 1)) +
  ggplot2::geom_line(ggplot2::aes(y = budget_gap,
                         color = "Budget"),
                     linewidth = 1.5,
                     color = "#F592A0") +  
  ggplot2::scale_y_continuous(
    expand = ggplot2::expansion(mult = c(0, .1)),
    labels = scales::label_number(scale_cut = scales::cut_short_scale())  ) +
#  scale_x_continuous(labels = scales::label_number(scale_cut = cut_short_scale())) +
 # ggplot2::facet_wrap(~ trans_year) +
  unhcrthemes::theme_unhcr(grid = "Y", axis = "X", 
                           axis_title = "X", font_size = 18,
                           legend = FALSE)+
  ggplot2::labs(
    title = paste0( "Budget Gap  (in %)"),
    subtitle =  paste0("In ", programme_lab, ctr_name,iati_identifier_ops, " recorded since ", year,""),
    x = "",
    y = "",
    caption = "Data Source: UNHCR IATI (International Aid Transparency Initiative)" ) 
 
  return(p)
    
}
