# WARNING - Generated by {fusen} from dev/dev_unhcr_programme.Rmd: do not edit by hand

#' Title
#' 
#' Description
#' 
#' @import ggplot2
#' @import dplyr
#' @import scales
#' @import unhcrthemes
#'
#' @export 
#' @return  a graph
#' @examples
#' show_indicators()
show_indicators <- function(){
    
}
