# WARNING - Generated by {fusen} from dev/dev_unhcr_programme.Rmd: do not edit by hand

#' show_indicators
#' 
#' How much indicators evolve over time against thresholds?
#' 
#' @param year A numeric value corresponding to the first year of focus until the most recent year within the dataset.
#' @param programme_lab A character vector corresponding to the name of the programme.
#' @param iati_identifier_ops A character vector corresponding to the name of the operation.
#' @param ctr_name A character vector corresponding to the name of the country.
#' @param  result_type_name either  "Impact"  "Outcome" "Output" - default is  "Outcome"  
#' 
#' @import ggplot2
#' @import dplyr
#' @import scales
#' @import unhcrthemes
#' @importFrom stats reorder
#'
#' @export 
#' 
#' @return  a graph
#' @examples
#' show_indicators(year = 2022, 
#'              programme_lab = NULL, 
#'              iati_identifier_ops = NULL, 
#'              ctr_name = "Brazil",
#'               result_type_name = "Outcome"
#'              )
show_indicators <- function(year, 
                        programme_lab = NULL, 
                        iati_identifier_ops = NULL, 
                        ctr_name = NULL ,
                       result_type_name = "Outcome") {
  
  
  # Check if only one argument is passed 
  if (!is.null(programme_lab) && !is.null(iati_identifier_ops)) {
    stop("Please pass only one of the arguments programme_lab or iati_identifier_ops.")
  } else if (!is.null(programme_lab) && !is.null(ctr_name)) {
    stop("Please pass only one of the arguments programme_lab or ctr_name.")
  } else if (!is.null(iati_identifier_ops) && !is.null(ctr_name)) {
    stop("Please pass only one of the arguments iati_identifier_ops or ctr_name.")
  }
  
  df <-  iati::dataResult |> 
         dplyr::left_join(iati::dataActivity, by= c("iati_identifier"))   
  
  if (!is.null(programme_lab)) {
    thisprogramme_lab <- programme_lab
    thisyear <-  year 
    thisresult_type_name <-  result_type_name
    df <- df |> 
      # levels(as.factor(df$result_type_name ))
      dplyr::filter( programmme_lab == thisprogramme_lab &
            year >= thisyear & 
             result_type_name ==  thisresult_type_name)
  } else if (!is.null(iati_identifier_ops)) {
    thisiati_identifier_ops <- iati_identifier_ops
    thisyear <-  year 
    thisresult_type_name <-  result_type_name
    df <- df |> 
      dplyr::filter(iati_identifier_ops == thisiati_identifier_ops &
            year >= thisyear & 
             result_type_name ==  thisresult_type_name)
  } else if (!is.null(ctr_name)) {
    thisctr_name <- ctr_name
    thisyear <-  year 
    thisresult_type_name <-  result_type_name
    df <- df |> 
      dplyr::filter( ctr_name == thisctr_name &
            year >= thisyear & 
            result_type_name ==  thisresult_type_name)
  }
   
  ## in order to compare indictors alltogether in the same country, we need to normalise them
  ## one way is to compute the distance to the target...
  ## names(df)
  df1 <- df  |> 
    dplyr::select(result_type_name ,  result_title, indicator_measure_name, result_indicator_title,
                  result_indicator_baseline_value, result_indicator_target_value,
                  result_indicator_baseline_location_ref, result_indicator_baseline_dimension_1,
                  result_indicator_baseline_dimension_value_1, result_indicator_baseline_dimension_2,
                  result_indicator_baseline_dimension_value_2) |>
      dplyr::mutate(  actual = as.numeric(result_indicator_baseline_value),
                      target = as.numeric(result_indicator_target_value),
                      
              ## Calculating gap to target        
                      gap_actual_target = - round( (  target - actual) /  target *100  ,2 ),
                      #gap_actual_target = dplyr::if_else(reverse == "TRUE", gap_actual_target * -1, gap_actual_target), 
                      gap_actual_target =   gap_actual_target , 
                      gap_color = dplyr::case_when(
                        gap_actual_target >= 0     ~ "green",
                        gap_actual_target < 0  & gap_actual_target >= -10    ~ "orange",
                        gap_actual_target < -10     ~ "red",  
                                                   TRUE ~ "") )     |> 
    dplyr::filter (! (is.na(actual)))  |> 
    dplyr::filter (! (is.nan(gap_actual_target))) |>
      #dplyr::arrange(desc(actual))
      dplyr::group_by( result_indicator_title) |>
      dplyr::arrange(desc( actual), .by_group=TRUE )  |> 
      dplyr::ungroup(result_indicator_title) |>
              
              
              ## Calculating gap to green threshold
              #dplyr::mutate(  gap_actual_green = - round( ( threshold_green - actual) /  threshold_green *100 ,2 ),
                      # gap_actual_green = dplyr::if_else(reverse == "TRUE", gap_actual_green * -1, gap_actual_green), 
                      # gap_color_green = dplyr::case_when(
                      #   gap_actual_green >= 5     ~ "green",
                      #   gap_actual_green < 5  & gap_actual_target >= -15    ~ "orange",
                      #   gap_actual_green < -15     ~ "red",  
                      #                              TRUE ~ "")  )     |> 

  ## Reshape the inidcator label... 
      dplyr::mutate( operation = as.character(glue::glue("{result_title}-
                                                         {result_indicator_title} /
                                                         {result_indicator_baseline_dimension_1}") ) )  
 
  ## case there's no data at all
  if( nrow(df1) == 0) {
        info <-  paste0("No gap analysis could be \n produced for \n outcome indicator values \n in ", 
                      programme_lab, ctr_name,iati_identifier_ops)
        p <- ggplot2::ggplot() +  
             ggplot2::annotate("text",  x = 1, y = 1, size = 12,
                                  label = info ) +  
             ggplot2::theme_void()
  
   } else if(nrow(df1)> 0) {
  
      ## and now the plot
      p <-      ggplot2::ggplot(  data = df1) +
        ggplot2::coord_flip()  + 
        # geom_col(   aes(x = stats::reorder(operation, - gap_actual_green), 
        #                 y = gap_actual_green ,
        #                 fill = gap_color_green ),
        #            # fill = "grey50",    
        #             alpha = 0.3,    
        #             width = 0.9,
        #            color = NA ) +
        ggplot2::geom_col(   
          ggplot2::aes(x = stats::reorder(operation, - gap_actual_target),
                       y = gap_actual_target,
                       fill = gap_color ),
                    #fill = "#0072BC",
                    width = 0.7,
                    color = NA ) +
        ggplot2::scale_fill_manual(values = c( "red" = "#D3212C",   
                                      "orange" = "#FF980E",
                                      "green" = "#069C56")) +
        ggplot2::geom_text( 
          ggplot2::aes(x = stats::reorder(operation, - gap_actual_target), 
                       y = gap_actual_target,
                       label = paste(round(gap_actual_target, 1), " %") ),
                   #hjust = 1.5, 
                   size = 2.5,
                   color = "black")  +
        # scale_y_continuous( label = scales::label_percent(accuracy = 0,
        #                                    suffix = "%") ) +
        ggplot2::scale_y_continuous( label =  scales::label_number(accuracy = 1, 
                                                          scale_cut = scales::cut_short_scale(),
                                                          suffix = "%") )+
        ggplot2::scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 120)) +
        unhcrthemes::theme_unhcr(font_size = 18, 
                                 axis_text_size = 9,
                                 grid = "X", 
                                 axis = "y") +
        ggplot2::theme(  #axis.text.y = ggtext::element_markdown(),
                legend.position = "none")+
        ggplot2::labs( x = "", y = "" ,
              title = stringr::str_wrap( 
                paste0("Outcome Indicators (RBM) | ", thisyear, " ", 
                        programme_lab, ctr_name,iati_identifier_ops ) ,
                100),
              subtitle = stringr::str_wrap( paste0( 
                "Gap in % between \"Actual\" reported value and the \"acceptable\" standard threshold" ) ,
                110),
              caption = stringr::str_wrap( "Data Source: UNHCR IATI (International Aid Transparency Initiative)" ,
              110) )  
      }
 
  return(p)
    
}
