# WARNING - Generated by {fusen} from dev/dev_unhcr_programme.Rmd: do not edit by hand

#' Title
#' 
#' @description What’s the breakdown of Earmarking Type (Un-earmarked, Tightly earmarked, etc.) \
#'  from Donor Funds by Year?  
#'  Where possible, UNHCR prefers to receive unearmarked funds, as this allows the agency 
#'  greater flexibility in allocating its resources as new needs emerge during the course of the year. 
#'  Should that not be possible, funds can also be softly earmarked. This could mean funds that 
#'  can be spent anywhere within a region or for a particular situation (for example, funds that have 
#'  to be spent to assist refugees from Syria, but which can be spent in any country hosting such 
#'  refugees). Earmarked funds would be a contribution that corresponds to a specific country but 
#'  can be spent on anything within that operation’s programme. Finally, tightly earmarked funds 
#'  are those that specify an activity or a population within a country’s programme.
#'  
#'  UNHCR charges an ISC -  Indirect Support Costs - rate of 6.5% on all of its earmarked contributions.
#'   This covers management and administration  costs at HQ and programme support costs 
#'   incurred at HQ and Regional Bureaux. 
#' 
#' @param year A numeric value corresponding to the first year of focus until the most recent year within the dataset.
#' @param programme_lab A character vector corresponding to the name of the programme.
#' @param iati_identifier_ops A character vector corresponding to the name of the operation.
#' @param ctr_name A character vector corresponding to the name of the country.
#' 
#' @import ggplot2
#' @import dplyr
#' @import scales
#' @import unhcrthemes
#'
#' @export 
#' @return  a graph
#' @examples
#' knitr::kable(iati::dataTransaction |>
#'                 dplyr::select(earmarking_name, earmarking_description)  |>
#'                 dplyr::distinct() |>
#'                 dplyr::filter(!(is.na(earmarking_name))))
#' show_earmarking(year = 2018,  
#'              ctr_name = "Brazil")
show_earmarking <- function(year, 
                        programme_lab = NULL, 
                        iati_identifier_ops = NULL, 
                        ctr_name = NULL  ) {
  
  
  # Check if only one argument is passed 
  if (!is.null(programme_lab) && !is.null(iati_identifier_ops)) {
    stop("Please pass only one of the arguments programme_lab or iati_identifier_ops.")
  } else if (!is.null(programme_lab) && !is.null(ctr_name)) {
    stop("Please pass only one of the arguments programme_lab or ctr_name.")
  } else if (!is.null(iati_identifier_ops) && !is.null(ctr_name)) {
    stop("Please pass only one of the arguments iati_identifier_ops or ctr_name.")
  }
  
  df <-  iati::dataTransaction |> 
         dplyr::left_join(iati::dataActivity, by= c("iati_identifier"))  
  
  if (!is.null(programme_lab)) {
    thisprogramme_lab <- programme_lab
    thisyear <-  year 
    df <- df |> 
      # levels(as.factor(df$programmme_lab))
      dplyr::filter( programmme_lab == thisprogramme_lab &
            year >= thisyear & 
             transaction_type_name ==  "Incoming Commitment")
  } else if (!is.null(iati_identifier_ops)) {
    thisiati_identifier_ops <- iati_identifier_ops
    thisyear <-  year 
    df <- df |> 
      dplyr::filter(iati_identifier_ops == thisiati_identifier_ops &
            year >= thisyear & 
             transaction_type_name ==  "Incoming Commitment")
  } else if (!is.null(ctr_name)) {
    thisctr_name <- ctr_name
    thisyear <-  year 
    df <- df |> 
      dplyr::filter( ctr_name == thisctr_name &
            year >= thisyear & 
             transaction_type_name ==  "Incoming Commitment")
  }
  # levels(as.factor(df$earmarking_name)) 
  
  df2 <- df |> 
    dplyr::group_by(year, earmarking_name) |>
    dplyr::summarise( transaction_value_USD = sum(transaction_value_USD , na.rm = TRUE)) |>
    dplyr::mutate(earmarking_name = as.character(earmarking_name) )  |>
    dplyr::mutate(earmarking_name = as.factor(earmarking_name) ) 
  
 
  palette_earmarking <- c("Earmarked" = "#e1cc0d",
                    "Softly Earmarked" = "#0072bc", 
                    "Tightly Earmarked" = "#ef4a60", 
                    "Unearmarked" = "#00b398" )
  
 p <- df2 |> 
#  dplyr::filter(transaction_value_USD  <= 1000000 & transaction_value_USD  > 1000) |> 
  ggplot2::ggplot(ggplot2::aes(y = transaction_value_USD ,
             x =  year,
             fill = earmarking_name)) +
  ggplot2::geom_bar(alpha = 0.9, stat = "identity") +
  #ggplot2::scale_fill_viridis_d(option = "inferno", na.value = "grey50") +
  ggplot2::scale_fill_manual(values = palette_earmarking,
                      drop = TRUE,
                      limits = force,
                      na.value = "grey50") +
  ggplot2::scale_y_continuous(
    expand = ggplot2::expansion(mult = c(0, .1)),
    labels = scales::label_number(scale_cut = scales::cut_short_scale())  ) +
#  scale_x_continuous(labels = scales::label_number(scale_cut = cut_short_scale())) +
 # ggplot2::facet_wrap(~ trans_year) +
  unhcrthemes::theme_unhcr(grid = "Y", axis = "X", axis_title = "X", font_size = 18)+
  ggplot2::labs(
    title = paste0("Commitment vs Earmarking (in USD)"),
    subtitle = paste0("Recorded in ", programme_lab, ctr_name,iati_identifier_ops, " since ", year,""),
    x = "",
    y = "",
    caption = "Source: Data published by UNHCR as part of the International Aid Transparency Initiative (IATI)" ) 
 
  return(p) 
}
