# WARNING - Generated by {fusen} from dev/dev_unhcr_programme.Rmd: do not edit by hand

#' show_indicators_time
#' 
#' How much indicators evolve over time against thresholds?
#' 
#' @param year A numeric value corresponding to the first year of focus until the most recent year within the dataset.
#' @param ctr_name A character vector corresponding to the name of the country.
#' @param programme_lab A character vector corresponding to the name of the programme.
#' @param iati_identifier_ops A character vector corresponding to the name of the operation.
#' @param  result_type_name either  "Impact"  "Outcome" "Output" - default is  "Outcome" 
#' @param  type  "deviation" showing difference between target and actual - or 
#'               "progress"  showing difference between baseline and actual 
#' 
#' @import ggplot2
#' @import dplyr
#' @import scales
#' @import unhcrthemes
#' @importFrom stats reorder
#'
#' @export 
#' 
#' @return  a graph
#' @examples
#' show_indicators_time(year = 2020,  
#'              ctr_name = "Brazil",
#'               result_type_name = "Outcome",
#'              type = "deviation"
#'              )
#' show_indicators_time(year =  2020, 
#'              ctr_name = "Brazil",
#'               result_type_name = "Impact",
#'              type = "deviation"
#'              )
#' show_indicators_time(year =  2020,  
#'              ctr_name = "Brazil",
#'               result_type_name = "Output",
#'              type = "deviation"
#'              )
#' show_indicators_time(year =  2020, 
#'              ctr_name = "Brazil",
#'               result_type_name = "Outcome",
#'              type = "progress"
#'              )
#' show_indicators_time(year =  2020, 
#'              ctr_name = "Brazil",
#'               result_type_name = "Impact",
#'              type = "progress"
#'              )
#' show_indicators_time(year =  2020, 
#'              ctr_name = "Brazil",
#'               result_type_name = "Output",
#'              type = "progress"
#'              )
show_indicators_time <- function(year, 
                        programme_lab = NULL, 
                        iati_identifier_ops = NULL, 
                        ctr_name = NULL ,
                       result_type_name = "Outcome",
                        type = "deviation") {
  
  
  # Check if only one argument is passed 
  if (!is.null(programme_lab) && !is.null(iati_identifier_ops)) {
    stop("Please pass only one of the arguments programme_lab or iati_identifier_ops.")
  } else if (!is.null(programme_lab) && !is.null(ctr_name)) {
    stop("Please pass only one of the arguments programme_lab or ctr_name.")
  } else if (!is.null(iati_identifier_ops) && !is.null(ctr_name)) {
    stop("Please pass only one of the arguments iati_identifier_ops or ctr_name.")
  }
  
  df <-  iati::dataResult |> 
         dplyr::left_join(iati::dataActivity, by= c("iati_identifier"))   
  
  if (!is.null(programme_lab)) {
    thisprogramme_lab <- programme_lab
    thisyear <-  year 
    thisresult_type_name <-  result_type_name
    df <- df |> 
      # levels(as.factor(df$result_type_name ))
      dplyr::filter( programmme_lab == thisprogramme_lab &
            year >= thisyear & 
             result_type_name ==  thisresult_type_name)  |>
      dplyr::left_join(iati::mapping_result, by= c("result_title"))  |>
      dplyr::distinct()
    
  } else if (!is.null(iati_identifier_ops)) {
    thisiati_identifier_ops <- iati_identifier_ops
    thisyear <-  year 
    thisresult_type_name <-  result_type_name
    df <- df |> 
      dplyr::filter(iati_identifier_ops == thisiati_identifier_ops &
            year >= thisyear & 
             result_type_name ==  thisresult_type_name)  |>
      dplyr::left_join(iati::mapping_result, by= c("result_title")) |>
      dplyr::distinct()
    
  } else if (!is.null(ctr_name)) {
    thisctr_name <- ctr_name
    thisyear <-  year 
    thisresult_type_name <-  result_type_name
    df <- df |> 
      dplyr::filter( ctr_name == thisctr_name &
            year >= thisyear & 
            result_type_name ==  thisresult_type_name)  |>
      dplyr::left_join(iati::mapping_result, by= c("result_title")) |>
      dplyr::distinct()
  }
   
  ## in order to compare indictors alltogether in the same country, we need to normalise them
  ## one way is to compute the distance to the target...
  ## names(df)
  
  #table(df$result_indicator_ascending, useNA = "ifany")
  df1 <- df  |> 
    dplyr::select(result_type_name ,  result_title, sector_rbm,
                  indicator_measure_name, result_indicator_title,
                  year,
                  
                  result_indicator_baseline_value, 
                  result_indicator_actual_value,
                  result_indicator_target_value,
                  result_indicator_target_value_1,
                  
                  result_indicator_baseline_location_ref, 
                  result_indicator_baseline_dimension_1,
                  result_indicator_baseline_dimension_value_1, 
                  result_indicator_baseline_dimension_2,
                  result_indicator_baseline_dimension_value_2,
                  result_indicator_ascending)  |>
  
     ## Quick fix in case ascending is not documented...
     dplyr::mutate(  result_indicator_ascending = dplyr::if_else( is.na(result_indicator_ascending), 
                                               
                                               "1", 
                                               result_indicator_ascending))   |>    
     
      dplyr::mutate(  actual = as.numeric(result_indicator_actual_value),
                      baseline = as.numeric(result_indicator_baseline_value),
                      target = as.numeric(result_indicator_target_value), 
                      ## Reshape the indicator label... 
                      operation = as.character(glue::glue("{result_indicator_title} / {result_indicator_target_value_1}") ), 
                      # operation = as.character(glue::glue("{result_indicator_title} / {result_title} -
                      #                                        {result_indicator_target_value_1}") ),  
                      
                      
              ## Calculating deviation to target        
                      deviation_actual_target =  round( ( actual - target ) / 
                                                           dplyr::if_else(target == 0, 1, target) * 
                                                           dplyr::if_else(target == 0, 1, 100) ,2 ),
               
                      ## Account for indicator direction
                      deviation_actual_target = dplyr::if_else(result_indicator_ascending == 0, 
                                                         deviation_actual_target * -1, 
                                                         deviation_actual_target),   
                      
                      deviation_color = dplyr::case_when(
                        deviation_actual_target >= -1     ~ "green",
                        deviation_actual_target < -1  & deviation_actual_target >= -15    ~ "orange",
                        deviation_actual_target < -15     ~ "red",  
                                                   TRUE ~ ""),
              ## Calculating progress to baseline..        
                      progress_baseline =  round( ( actual - baseline) / 
                                                           dplyr::if_else(baseline == 0, 1, baseline) * 
                                                           dplyr::if_else(baseline == 0, 1, 100)  ,2 ), 
                      ## Account for indicator direction
                      progress_baseline = dplyr::if_else(result_indicator_ascending == 0, 
                                                         progress_baseline * -1, 
                                                         progress_baseline),   
                      progress_color = dplyr::case_when(
                        progress_baseline >= -1     ~ "green",
                        progress_baseline < -1  & progress_baseline >= -15    ~ "orange",
                        progress_baseline < -15     ~ "red",  
                                                   TRUE ~ "")
              
              )    
  
  ### Type of chart to build...
  if(type == "deviation") {
    
      df1 <- df1 |> 
          ## Filter out - when no data...
          dplyr::filter (! (is.na(actual)))  |> 
          dplyr::filter (! (is.na(target)))  |> 
          dplyr::filter (! (is.nan(deviation_actual_target))) |>
          #dplyr::arrange(desc(actual))
          dplyr::group_by( result_indicator_title) |>
          dplyr::arrange(desc( actual), .by_group=TRUE )  |> 
          dplyr::ungroup(result_indicator_title)
     
          ## case there's no data at all
          if( nrow(df1) == 0) {
                info <-  paste0("No deviation - actual to target - \n comparative analysis \n  could be produced for \n",
                                result_type_name, " indicator values \n in ", 
                              programme_lab, ctr_name,iati_identifier_ops, " for year: ", year)
                p <- ggplot2::ggplot() +  
                     ggplot2::annotate("text",  x = 1, y = 1, size = 12,
                                          label = info ) +  
                     ggplot2::theme_void()
          
           } else if(nrow(df1)> 0) {
              ## and now the plot
              p <-  ggplot2::ggplot( df1, 
                 ggplot2::aes(x = year,
                          y = deviation_actual_target,
                   #shape = indicator_measure_name,
                   color = sector_rbm)) + 
  ggplot2::geom_jitter(position=position_jitter(0.2),
                       shape = 17,
                       size = 3) +
    ggplot2::stat_summary(fun.data=mean_sdl, #mult=1, 
                   geom="pointrange", color="grey", size = 1)   + 
    geom_hline(yintercept= 0, color="red") +
 # ggplot2::scale_color_viridis_d(option = "inferno", na.value = "grey50") + 
    ggplot2::scale_colour_brewer(palette = "Paired") +
  ggplot2::scale_y_continuous( label =  scales::label_number(accuracy = 1, 
                                                             scale_cut = scales::cut_short_scale(),
                                                             suffix = "%") )+
  ggplot2::scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 120)) +
  unhcrthemes::theme_unhcr(font_size = 22, 
                           axis_text_size = 9,
                           grid = "Y", 
                           axis = "y") +
    ggplot2::theme( legend.direction = "vertical",
                    legend.box = "horizontal",
                    legend.position = "right")+
  
  ggplot2::labs( x = "", y = "" ,
                 title = stringr::str_wrap( 
                   paste0( result_type_name, " Indicators   ", 
                           programme_lab, ctr_name,iati_identifier_ops ) ,
                   100), 
                 subtitle = stringr::str_wrap( paste0( 
                         "Deviation between reported \"Actual\" value and programmatic \"Target\" (in %)" ) ,
                      110),
                 caption = stringr::str_wrap( 
                   "Data Source: UNHCR IATI (International Aid Transparency Initiative)" ,
                   110) )  
           }
    } else if( type == "progress")  {
      
      df1 <- df1 |> 
        ## Filter out - when no data...
        dplyr::filter (! (is.na(actual)))  |> 
        dplyr::filter (! (is.na(baseline)))  |> 
        dplyr::filter (! (is.nan(progress_baseline))) |>
        #dplyr::arrange(desc(actual))
        dplyr::group_by( result_indicator_title) |>
        dplyr::arrange(desc( actual), .by_group=TRUE )  |> 
        dplyr::ungroup(result_indicator_title)
 
        ## case there's no data at all
        if( nrow(df1) == 0) {
              info <- paste0("No progress - actual to baseline - \n comparative analysis \n  could be produced for \n",
                                  result_type_name, " indicator values \n in ", 
                                programme_lab, ctr_name,iati_identifier_ops, " for year: ", year)
              p <- ggplot2::ggplot() +  
                   ggplot2::annotate("text",  x = 1, y = 1, size = 12,
                                        label = info ) +  
                   ggplot2::theme_void()
        
         } else if(nrow(df1)> 0) {
            ## and now the plot
            p <-  ggplot2::ggplot( df1, 
                 ggplot2::aes(x = year,
                          y = progress_baseline,
                   #shape = indicator_measure_name,
                   color = sector_rbm)) + 
        ggplot2::geom_jitter(position=position_jitter(0.2),
                             shape = 17,
                             size = 3) +
          ggplot2::stat_summary(fun.data=mean_sdl, #mult=1, 
                         geom="pointrange", color="grey", size = .3)   + 
          geom_hline(yintercept= 0, color="red") +
       # ggplot2::scale_color_viridis_d(option = "inferno", na.value = "grey50") + 
          ggplot2::scale_colour_brewer(palette = "Paired") +
        ggplot2::scale_y_continuous( label =  scales::label_number(accuracy = 1, 
                                                                   scale_cut = scales::cut_short_scale(),
                                                                   suffix = "%") )+
        ggplot2::scale_x_discrete(labels = function(x) stringr::str_wrap(x, width = 120)) +
        unhcrthemes::theme_unhcr(font_size = 22, 
                                 axis_text_size = 9,
                                 grid = "Y", 
                                 axis = "y") +
          ggplot2::theme( legend.direction = "vertical",
                          legend.box = "horizontal",
                          legend.position = "right")+
        
        ggplot2::labs( x = "", y = "" ,
                       title = stringr::str_wrap( 
                         paste0( result_type_name, " Indicators   ", 
                                 programme_lab, ctr_name,iati_identifier_ops ) ,
                         100),
                subtitle = stringr::str_wrap( paste0( 
                      "Progress comparison between \"Actual\" reported value and their \"baseline\" (in %)" ) ,
                         110),
                       caption = stringr::str_wrap( 
                         "Data Source: UNHCR IATI (International Aid Transparency Initiative)" ,
                         110) )  
             }
  }
  return(p)
    
}
