# WARNING - Generated by {fusen} from dev/dev_unhcr_programme.Rmd: do not edit by hand

#' show_top_donors
#'
#' @description Who are the main donors by country in terms of transaction? 
#' 
#' @param year year to select starting from 2016 - could be one year or a list
#' @param programme_lab A character vector corresponding to the name of the programme.
#' @param iati_identifier_ops A character vector corresponding to the name of the operation.
#' @param ctr_name A character vector corresponding to the name of the country. 
#' @param top_n top n donors to show - the rest being lumped together
#' 
#' @import ggplot2
#' @import dplyr
#' @import scales
#' @import unhcrthemes
#'
#' @export 
#'
#' @return  a graph
#' @examples
#' show_top_donors(year = 2022,
#'            ctr_name = "Brazil", 
#'            top_n = 5)
#' show_top_donors(year = 2020,
#'            ctr_name = "Brazil", 
#'            top_n = 10)
show_top_donors <- function(year, 
                        programme_lab = NULL, 
                        iati_identifier_ops = NULL, 
                        ctr_name = NULL, 
                        top_n = 5) {
  
  ## Check year is after or equal 2016
  
  
  # Check if only one argument is passed 
  if (!is.null(programme_lab) && !is.null(iati_identifier_ops)) {
    stop("Please pass only one of the arguments programme_lab or iati_identifier_ops.")
  } else if (!is.null(programme_lab) && !is.null(ctr_name)) {
    stop("Please pass only one of the arguments programme_lab or ctr_name.")
  } else if (!is.null(iati_identifier_ops) && !is.null(ctr_name)) {
    stop("Please pass only one of the arguments iati_identifier_ops or ctr_name.")
  }
  
  df <-  iati::dataTransaction |> 
         dplyr::left_join(iati::dataActivity, by= c("iati_identifier"))  
  
  ## Filtering
  if (!is.null(programme_lab)) {
    thisprogramme_lab <- programme_lab
    thisyear <-  year 
    df <- df |> 
      # levels(as.factor(df$programmme_lab))
      dplyr::filter( programmme_lab == thisprogramme_lab &
            year == thisyear & 
             transaction_type_name ==  "Incoming Commitment")
  } else if (!is.null(iati_identifier_ops)) {
    thisiati_identifier_ops <- iati_identifier_ops
    thisyear <-  year 
    df <- df |> 
      dplyr::filter(iati_identifier_ops == thisiati_identifier_ops &
            year == thisyear & 
             transaction_type_name ==  "Incoming Commitment")
  } else if (!is.null(ctr_name)) {
    thisctr_name <- ctr_name
    thisyear <-  year 
    df <- df |> 
      dplyr::filter( ctr_name == thisctr_name &
            year == thisyear & 
             transaction_type_name == "Incoming Commitment")
  }
   
   
  df2 <- df |>
    dplyr::group_by(year, transaction_provider_org) |>
    dplyr::summarise( transaction_value_USD = sum(transaction_value_USD , na.rm = TRUE)) |>
    dplyr::mutate( transaction_provider_org = as.character(transaction_provider_org) )  |>
    dplyr::mutate( transaction_provider_org = as.factor(transaction_provider_org) )  |>
    dplyr::mutate( transaction_provider_org = forcats::fct_lump_n(
        f = transaction_provider_org,
        n = top_n,  #### Parameter
        w = transaction_value_USD,
        other_level = 'Other Partners',
        ties.method = "last")    ) |>
    dplyr::group_by(year, transaction_provider_org) |>
    dplyr::summarise( transaction_value_USD = sum(transaction_value_USD , na.rm = TRUE)) |>
    dplyr::mutate(transaction_provider_org = as.character(transaction_provider_org) )  |>
    dplyr::mutate(transaction_provider_org = as.factor(transaction_provider_org) )
  
  #levels(as.factor(df2$transaction_provider_org))

  
 p <- df2 |> 
#  dplyr::filter(transaction_value_USD  <= 1000000 & transaction_value_USD  > 1000) |> 
  ggplot2::ggplot(ggplot2::aes(y = transaction_value_USD ,
             x = stats::reorder( transaction_provider_org, transaction_value_USD) )) +
  ggplot2::geom_bar(alpha = 0.9, stat = "identity", fill = "#0072BC") +
  ggplot2::coord_flip() +
  ggplot2::scale_y_continuous(
    expand = ggplot2::expansion(mult = c(0, .1)),
    labels = scales::label_number(scale_cut = scales::cut_short_scale())  ) +
#  scale_x_continuous(labels = scales::label_number(scale_cut = cut_short_scale())) +
 # ggplot2::facet_wrap(~ trans_year) +
  unhcrthemes::theme_unhcr(grid = "X", axis = "X", axis_title = "X", font_size = 18)+
  ggplot2::labs(
    title = paste0("Top ",top_n ," donors (in USD)"),
    subtitle = paste0("Incoming Commitment Recorded in ", programme_lab, ctr_name,iati_identifier_ops, " | ", year,""),
    x = "",
    y = "",
    caption = "Source: Data published by UNHCR as part of the International Aid Transparency Initiative (IATI)" ) 
 
  return(p)
}
