# Generated by fusen: do not edit by hand

#' Ploting implementers
#'
#' 
#' @param year year to select starting from 2016 - could be one year or a list
#' @param geo Region or Country or Site
#' @param transtype Transaction type
#' 
#' @inheritParams ggplot2::ggplot
#'
#' @export
#'
#' @examples
#' show_implementers(year = 2020,
#'             geo = "The Americas",
#'             transtype = "11" ) 
show_implementers <- function(year, 
                        geo,
                        transtype  ) {
  #require(ggplot2)
  require(tidyverse)
  require(scales)
p<- iati::dataTransaction %>%
  dplyr::left_join(iati::codeOrganisationType %>%
                     dplyr::mutate(transorg_type = name) %>%
                     dplyr::select(code, transorg_type) ,
                   by= c("transaction_provider_org_type" = "code")) %>%
  dplyr::left_join(iati::codeTransactionType %>%
                     dplyr::mutate(TransactionType = name,
                                   TransactionDescr = description) %>%
                     dplyr::select(code, TransactionType,TransactionDescr  ) ,
                   by= c("transaction_type_code" = "code")) %>%
  dplyr::left_join(iati::codeAidTypeVocabulary %>%
                     dplyr::mutate(aidvocabulary1 = name,
                                   aidvocabularyDescr1 = description) %>%
                     dplyr::select(code, aidvocabulary1,aidvocabularyDescr1  ) ,
                   by= c("transaction_aid_type_vocabulary_1" = "code")) %>%
  dplyr::left_join(iati::codeAidType %>%
                     dplyr::mutate(AidType1 = name,
                                   AidTypeDescr1 = description) %>%
                     dplyr::select(code, AidType1,AidTypeDescr1  ) ,
                   by= c("transaction_aid_type_code_1" = "code")) %>%
  dplyr::left_join(iati::codeAidTypeVocabulary %>%
                     dplyr::mutate(aidvocabulary2 = name,
                                   aidvocabularyDescr2 = description) %>%
                     dplyr::select(code, aidvocabulary2,aidvocabularyDescr2  ) ,
                   by= c("transaction_aid_type_vocabulary_2" = "code"))%>%
  dplyr::left_join(iati::codeAidType %>%
                     dplyr::mutate(AidType2 = name,
                                   AidTypeDescr2 = description) %>%
                     dplyr::select(code, AidType2,AidTypeDescr2  ) ,
                   by= c("transaction_aid_type_code_2" = "code")) %>%
  
  dplyr::left_join(iati::dataActivity %>%
                     dplyr::left_join(iati::codeOrganisationType %>%
                                        dplyr::mutate(report_org_type = name) %>%
                                        dplyr::select(code, report_org_type) ,
                                      by= c("reporting_org_type" = "code")) %>%
                     dplyr::left_join(iati::codeActivityScope %>%
                                        dplyr::mutate(codeActivityScope = name) %>%
                                        dplyr::select(code, codeActivityScope) ,
                                      by= c("activity_scope_code" = "code"))  %>%
                     dplyr::left_join(iati::codeCountry %>%
                                        dplyr::mutate(recipientCountry = name) %>%
                                        dplyr::select(code, recipientCountry) ,
                                      by= c("recipient_country_code" = "code")) %>%
                     dplyr::left_join(iati::codeRegion %>%
                                        dplyr::mutate(recipientRegion = name) %>%
                                        dplyr::select(code, recipientRegion) ,
                                      by= c("recipient_region_code" = "code")) %>%
                     
                     dplyr::left_join(iati::codeActivityStatus %>%
                                        dplyr::mutate(ActivityStatus = name) %>%
                                        dplyr::select(code, ActivityStatus) ,
                                      by= c("activity_status_code" = "code")) %>%
                     dplyr::left_join(iati::codeCollaborationType %>%
                                        dplyr::mutate(CollaborationType = name) %>%
                                        dplyr::select(code, CollaborationType) ,
                                      by= c("collaboration_type_code" = "code"))  ,
                   by= c("iati_identifier")) %>%
  
  ## Add filters 
  dplyr::filter(transaction_type_code == transtype, ## Add filters transaction type 
                lubridate::year(transaction_date) >= year  ## Add filters transaction type 
                ) %>%
  
  dplyr::mutate(
    trans_year = lubridate::year(transaction_date),
    month_trans = factor(format(transaction_date, "%b"), month.abb, ordered = TRUE)
  ) %>%
  dplyr::select(trans_year, month_trans, transaction_value) %>%
#  dplyr::filter(transaction_value <= 1000000 & transaction_value > 1000) %>%
  ggplot2::ggplot(aes(y = transaction_value,
             x = month_trans )) +
  geom_bar(alpha = 0.9, stat = "identity") +
  #scale_x_continuous(labels = scales::label_number(scale_cut = cut_short_scale())) +
  facet_wrap(~ trans_year) +
  theme_minimal() +
 # unhcRstyle::unhcr_theme() +
  labs(
    title = "Donations received by UNHCR",
    subtitle = "Between 2014 and 2022",
    x = "",
    y = "",
    caption = "IATI Package - github.com/unhcr-americas/iati"
  ) 
  p
}
