# WARNING - Generated by {fusen} from dev/dev_unhcr_programme.Rmd: do not edit by hand

#' show_budget_gap
#' 
#' UNHCR budgets are needs-based: it represents the total amount
#' of money that would be required were UNHCR to meet all of the needs that it is seeking to address.
#' 
#' @param year A numeric value corresponding to the first year of focus until the most recent year within the dataset.
#' @param programme_lab A character vector corresponding to the name of the programme.
#' @param iati_identifier_ops A character vector corresponding to the name of the operation.
#' @param ctr_name A character vector corresponding to the name of the country.
#' @param weight_by list of population group to weight the budget - 
#'                   "refugees", "asylum_seekers",
#'                    "returned_refugees" "idps",
#'                    "returned_idps", "stateless", 
#'                    "ooc", "oip"  
#'                   default is null.
#' 
#' @import ggplot2
#' @import dplyr
#' @import tidyselect
#' @import scales
#' @import unhcrthemes 
#'
#' @export 
#' @return  a graph
#' @examples
#' show_budget_gap(year = c(2018, 2019,2020, 2021, 2022, 2023), 
#'              ctr_name = "Brazil")
#' show_budget_gap(year = c(2018, 2019,2020, 2021, 2022, 2023), 
#'              ctr_name = "Brazil",
#'              weight_by = c("refugees", "oip"))
show_budget_gap <- function(year, 
                        programme_lab = NULL, 
                        iati_identifier_ops = NULL, 
                        ctr_name = NULL ,
                        weight_by = NULL ) {
  
  
  # Check if only one argument is passed 
  if (!is.null(programme_lab) && !is.null(iati_identifier_ops)) {
    stop("Please pass only one of the arguments programme_lab or iati_identifier_ops.")
  } else if (!is.null(programme_lab) && !is.null(ctr_name)) {
    stop("Please pass only one of the arguments programme_lab or ctr_name.")
  } else if (!is.null(iati_identifier_ops) && !is.null(ctr_name)) {
    stop("Please pass only one of the arguments iati_identifier_ops or ctr_name.")
  }
  
  df <-  iati::dataTransaction |> 
         dplyr::left_join(iati::dataActivity, by= c("iati_identifier"))  
  
  if (!is.null(programme_lab)) {
    thisprogramme_lab <- programme_lab
    thisyear <-  year 
    df <- df |> 
      # levels(as.factor(df$programmme_lab))
      dplyr::filter( programmme_lab == thisprogramme_lab &
            year %in% thisyear & 
             transaction_type_name ==  "Expenditure")
  } else if (!is.null(iati_identifier_ops)) {
    thisiati_identifier_ops <- iati_identifier_ops
    thisyear <-  year 
    df <- df |> 
      dplyr::filter(iati_identifier_ops == thisiati_identifier_ops &
            year %in% thisyear & 
             transaction_type_name ==  "Expenditure")
  } else if (!is.null(ctr_name)) {
    thisctr_name <- ctr_name
    thisyear <-  year 
    df <- df |> 
      dplyr::filter( ctr_name == thisctr_name &
            year %in% thisyear & 
             transaction_type_name ==  "Expenditure")
  }
  
   df2 <-  df  |> 
        dplyr::group_by(iati_identifier, year) |>
        dplyr::summarise(transaction_value_USD= sum(transaction_value, na.rm = TRUE)) |>
        dplyr::left_join(iati::dataBudget |> 
                          dplyr::mutate(budget_value= as.numeric(budget_value)) |>
                          dplyr::group_by(iati_identifier) |>
                          dplyr::summarise(budget_value= sum(budget_value, na.rm = TRUE))  
                            , by= c("iati_identifier"))  |>
     dplyr::select(iati_identifier, year,budget_value,   transaction_value_USD )  |>
     dplyr::mutate(budget_gap = (budget_value - transaction_value_USD) / budget_value *100) 
   
 
   
    if (  !is.null(weight_by) &&  !all(weight_by %in% c("all",  "refugees", "asylum_seekers",
                                                   "returned_refugees", "idps",
                                                   "returned_idps", "stateless", 
                                                   "ooc", "oip"  ))  ) {
     stop("weight_by is used but the population filter is not correctly set up...\n
          it should be among: refugees, asylum_seekers, returned_refugees, idps,
          returned_idps, stateless,  ooc, oip")
    } 
    ## if "all"  
   if (  !is.null(weight_by) && "all" %in% weight_by) { 
     weight_by <- c("refugees", "asylum_seekers",
                    "returned_refugees", "idps",
                    "returned_idps", "stateless", 
                    "ooc", "oip"  )} else {  weight_by <- weight_by }
   
   ## Calculate weight
   if (!is.null(weight_by) && !is.null(ctr_name) ) {
     ctrstat <- refugees::population |>
            dplyr::filter( year>= thisyear & 
                             coa_name == thisctr_name) |>
            dplyr::group_by(year, coa_name) |>
            dplyr::summarise(refugees = sum(refugees, na.rm = TRUE),
                             asylum_seekers = sum(asylum_seekers, na.rm = TRUE),
                              returned_refugees = sum(returned_refugees, na.rm = TRUE),
                              idps = sum(idps, na.rm = TRUE),
                              returned_idps = sum(returned_idps , na.rm = TRUE),
                              stateless = sum(stateless, na.rm = TRUE),
                              ooc = sum( ooc, na.rm = TRUE),
                              oip = sum(oip, na.rm = TRUE)) |>
            dplyr::select(year, coa_name, all_of(weight_by) ) |>
            dplyr::mutate(year = as.factor(year) ) |>
            dplyr::mutate( weight = rowSums(
                                   dplyr::across(tidyselect::where(is.numeric))))
     
      df2 <-  df2 |>
        dplyr::left_join(ctrstat |> 
                         dplyr::select(year, weight)   , by = c("year")) |>
        dplyr::mutate(budget_value = round(budget_value / weight,1),   
                      transaction_value_USD = round(transaction_value_USD  / weight,1))
      df2 <-  df2 |>
       dplyr::mutate(budget_gap2 = (budget_value - transaction_value_USD) / budget_value *100) 
     
    } 
   
 subtitt <- if( is.null(weight_by)) {
   paste0("In ", programme_lab, ctr_name,iati_identifier_ops, "")
   } else {
   paste0("Weighted by total number of individual ", 
          paste(weight_by, collapse = ', '),
          " in ", 
          programme_lab, ctr_name,iati_identifier_ops, "")
     }
 
 p <- df2 |> 
#  dplyr::filter(transaction_value_USD   <= 1000000 & transaction_value_USD  > 1000) |> 
  ggplot2::ggplot(ggplot2::aes(x =  year, group = 1)) +
  ggplot2::geom_line(ggplot2::aes(y = budget_gap,
                         color = "Budget"),
                     linewidth = 1.5,
                     color = "#F592A0") +  
  ggplot2::scale_y_continuous(  limits=c(0,100)) +
  # ggplot2::scale_y_continuous(
  #   #expand = ggplot2::expansion(mult = c(0, .1)),
  #   labels = scales::label_number(scale_cut = scales::cut_short_scale())  ) +
#  scale_x_continuous(labels = scales::label_number(scale_cut = cut_short_scale())) +
 # ggplot2::facet_wrap(~ trans_year) +
  unhcrthemes::theme_unhcr(grid = "Y", axis = "X", 
                           axis_title = "X", font_size = 18,
                           legend = FALSE)+
  ggplot2::labs(
    title = paste0( "Budget Gap  (in %)"),
    subtitle =   subtitt ,
    x = "",
    y = "",
    caption = "Source: Data published by UNHCR as part of the International Aid Transparency Initiative (IATI). UNHCR budget is needs-based. It represents the total amount of money that would be required were UNHCR to meet all of the needs that it is seeking to address." ) 
 
  return(p)
    
}
