# WARNING - Generated by {fusen} from dev/dev_unhcr_programme.Rmd: do not edit by hand

#' show_transaction_flow
#' 
#' Flow diagramme of transations
#' 
#' 
#' @param year A numeric value corresponding to the first year of focus until the most recent year within the dataset.
#' @param programme_lab A character vector corresponding to the name of the programme.
#' @param iati_identifier_ops A character vector corresponding to the name of the operation.
#' @param ctr_name A character vector corresponding to the name of the country.
#' 
#' @import ggplot2
#' @import dplyr
#' @import scales
#' @import unhcrthemes
#' @import ggsankey
#'
#' @export 
#' @return  a graph
#' @examples
#' show_transaction_flow(year = 2020, 
#'                    ctr_name = "Brazil")
#'
#' show_transaction_flow(year = 2023, 
#'                    ctr_name = "Brazil")
show_transaction_flow <- function(year, 
                        programme_lab = NULL, 
                        iati_identifier_ops = NULL, 
                        ctr_name = NULL  ) {
  
  
  # Check if only one argument is passed 
  if (!is.null(programme_lab) && !is.null(iati_identifier_ops)) {
    stop("Please pass only one of the arguments programme_lab or iati_identifier_ops.")
  } else if (!is.null(programme_lab) && !is.null(ctr_name)) {
    stop("Please pass only one of the arguments programme_lab or ctr_name.")
  } else if (!is.null(iati_identifier_ops) && !is.null(ctr_name)) {
    stop("Please pass only one of the arguments iati_identifier_ops or ctr_name.")
  }
  
  df <-  iati::dataTransaction |> 
         dplyr::left_join(iati::dataActivity, by= c("iati_identifier"))  
  
  if (!is.null(programme_lab)) {
    thisprogramme_lab <- programme_lab
    thisyear <-  year 
    df <- df |> 
      # levels(as.factor(df$programmme_lab))
      dplyr::filter( programmme_lab == thisprogramme_lab &
            year >= thisyear & 
             transaction_type_name ==  "Incoming Commitment")
  } else if (!is.null(iati_identifier_ops)) {
    thisiati_identifier_ops <- iati_identifier_ops
    thisyear <-  year 
    df <- df |> 
      dplyr::filter(iati_identifier_ops == thisiati_identifier_ops &
            year >= thisyear & 
             transaction_type_name ==  "Incoming Commitment")
  } else if (!is.null(ctr_name)) {
    thisctr_name <- ctr_name
    thisyear <-  year 
    df <- df |> 
      dplyr::filter( ctr_name == thisctr_name &
            year >= thisyear & 
             transaction_type_name ==  "Incoming Commitment")
  }
 
  df1 <- df |>
         ggsankey::make_long(earmarking_name, 
                      year, 
                      provider_org_type_name,
                      transaction_provider_org, 
                      value = transaction_value_USD)

  p <- ggplot2::ggplot(df1, 
              ggplot2::aes(x = x,
                 next_x = next_x,
                 node = node,
                 next_node = next_node,
                 fill = factor(node),
                 label = node)) +
        ggsankey::geom_sankey(flow.alpha = 0.5, node.color = 1) +
        ggsankey::geom_sankey_label(size = 3.5, color = 1, fill = "white") +
        ggplot2::scale_fill_viridis_d() +
        ggsankey::theme_sankey(base_size = 12) +
        unhcrthemes::theme_unhcr(font_size = 18, grid = FALSE, axis = FALSE,  legend = FALSE)   +
        ggplot2::theme(axis.text.y = element_blank()) + 
        ggplot2::labs(
              x = "",
              y = "",
              title = stringr::str_wrap(paste0("Commitment | ", programme_lab, ctr_name,iati_identifier_ops, "" ), 60),
              subtitle = stringr::str_wrap(paste0(" "), 80),
              caption = "Source: Data published by UNHCR as part of the International Aid Transparency Initiative (IATI)" )  
  
  return(p)
    
}
