# Generated by fusen: do not edit by hand

#' Ploting Donors
#'
#' 
#' @param year year to select starting from 2016 - could be one year or a list
#' @param geo Region or Country or Site
#' @param sector Sectors
#' @param metric Metrics could be USD or Number of project
#' 
#' @inheritParams ggplot2::ggplot
#'
#' @return
#' Median of vector x
#' @export
#'
#' @examples
#' show_donors(1:12)
show_donors <- function(year, geo, sector, metric) {
  1
}
