# WARNING - Generated by {fusen} from dev/dev_unhcr_programme.Rmd: do not edit by hand

#' show_sectors
#' 
#' @description  What are the most funded sectors per country (Expenditure evolution per impact /outcome area)?  
#' 
#' @param year A numeric value corresponding to the first year of focus until the most recent year within the dataset.
#' @param programme_lab A character vector corresponding to the name of the programme.
#' @param iati_identifier_ops A character vector corresponding to the name of the operation.
#' @param ctr_name A character vector corresponding to the name of the country.
#' @param sector_vocabulary_name sector_vocabulary
#' 
#' @import ggplot2
#' @import dplyr
#' @import scales
#' @import unhcrthemes
#' @importFrom stats reorder
#'
#' @export 
#' @return  a graph
#' @examples
#'
#' knitr::kable( iati::dataSector |> 
#'                 dplyr::select( sector_vocabulary_name, sector_vocabulary_description) |>
#'                 dplyr::distinct())
#'
#' show_sectors(year = 2018, 
#'              programme_lab = NULL, 
#'              iati_identifier_ops = NULL, 
#'              ctr_name = "Syria",
#'             sector_vocabulary_name = "Reporting Organisation 2")
show_sectors <- function(year, 
                         programme_lab = NULL, 
                         iati_identifier_ops = NULL, 
                         ctr_name = NULL,
                         sector_vocabulary_name = "Reporting Organisation 2"){
  # Check if only one argument is passed 
  if (!is.null(programme_lab) && !is.null(iati_identifier_ops)) {
    stop("Please pass only one of the arguments programme_lab or iati_identifier_ops.")
  } else if (!is.null(programme_lab) && !is.null(ctr_name)) {
    stop("Please pass only one of the arguments programme_lab or ctr_name.")
  } else if (!is.null(iati_identifier_ops) && !is.null(ctr_name)) {
    stop("Please pass only one of the arguments iati_identifier_ops or ctr_name.")
  }
  
  # Join dataActivity and dataSector on iati_identifier 
  df <- iati::dataSector |>
    dplyr::left_join(iati::dataActivity,  by = c("iati_identifier"))
  
  if (!is.null(programme_lab)) {
    thisprogramme_lab <- programme_lab
    thisyear <- year
    thissector_vocabulary <- sector_vocabulary
    df <- df |> 
      dplyr::filter(programmme_lab == thiprogramme_lab &
            year > thisyear & 
            sector_vocabulary_name ==  thissector_vocabulary_name)
  } else if (!is.null(iati_identifier_ops)) {
    thisiati_identifier_ops <- iati_identifier_ops
    thisyear <- year
    thissector_vocabulary_name <- sector_vocabulary_name
    df <- df |> 
      dplyr::filter(iati_identifier_ops == thisiati_identifier_ops &
            year > thisyear & 
            sector_vocabulary_name ==  thissector_vocabulary_name)
  } else if (!is.null(ctr_name)) {
    thisctr_name <- ctr_name
    thisyear <- year
    thissector_vocabulary_name <- sector_vocabulary_name
    df <- df |> 
      dplyr::filter(ctr_name == thisctr_name &
            year > thisyear & 
            sector_vocabulary_name ==  thissector_vocabulary_name)
  }
  
  df <- df |> 
    dplyr::group_by(sector_desc, year) |> 
    dplyr::summarise(sector_pct = mean( as.numeric(sector_pct)) ) |> 
   # dplyr::summarise(sector_pct = sum(sector_pct, na.rm = TRUE)/sum(df$sector_pct, na.rm = TRUE)*100) |> 
  #  top_n(5, wt = sector_pct) |> 
    dplyr::mutate(sector_desc = as.factor(sector_desc))
  

  p <-  ggplot2::ggplot(data = df, 
                        ggplot2::aes(x = stats::reorder(sector_desc, sector_pct),
                                 y = sector_pct
                                 )) +
    unhcrthemes::theme_unhcr(grid = TRUE, axis = "Y", axis_title = "Sector Percentage") +
    ggplot2::geom_bar(stat = "identity") +
    ggplot2::coord_flip()+
    ggplot2::facet_wrap( ggplot2::vars(year)) +
    ggplot2::scale_fill_viridis_d(option = "inferno", na.value = "grey50") +
    ggplot2::scale_y_continuous(expand = ggplot2::expansion(mult = c(0, .1)), labels = scales::label_number(scale_cut = scales::cut_short_scale())) +
    ggplot2::labs(title = "Share of budget per sectors for the selected year", 
         x = "Sectors", y = "% of Total Funding", 
         caption = "Data Source: UNHCR IATI (International Aid Transparency Initiative)") 

    
 
  return(p)
}
