# WARNING - Generated by {fusen} from dev/dev_unhcr_programme.Rmd: do not edit by hand

#' show_partnership
#' 
#' @description How organisations partner together? 
#'
#' @param year A numeric value corresponding to the year to be displayed
#' @param programme_lab A character vector corresponding to the name of the programme.
#' @param iati_identifier_ops A character vector corresponding to the name of the operation.
#' @param ctr_name A character vector corresponding to the name of the country.
#' 
#' @import ggplot2
#' @import dplyr
#' @import scales
#' @import unhcrthemes
#'
#' @export 
#' @return  a graph
#' @examples
#' show_partnership(year = 2022,
#'            ctr_name = "Brazil" ) 
show_partnership <- function( year, 
                        programme_lab = NULL, 
                        iati_identifier_ops = NULL, 
                        ctr_name = NULL  ) {
  
  
  # Check if only one argument is passed 
  if (!is.null(programme_lab) && !is.null(iati_identifier_ops)) {
    stop("Please pass only one of the arguments programme_lab or iati_identifier_ops.")
  } else if (!is.null(programme_lab) && !is.null(ctr_name)) {
    stop("Please pass only one of the arguments programme_lab or ctr_name.")
  } else if (!is.null(iati_identifier_ops) && !is.null(ctr_name)) {
    stop("Please pass only one of the arguments iati_identifier_ops or ctr_name.")
  }
  
  df <-  iati::dataParticipating_org |> 
         dplyr::left_join(iati::dataActivity, by= c("iati_identifier"))  
  
  if (!is.null(programme_lab)) {
    thisprogramme_lab <- programme_lab
    thisyear <-  year
    df <- df |> 
      # levels(as.factor(df$programmme_lab))
      dplyr::filter( programmme_lab == thisprogramme_lab &
            year == thisyear )
  } else if (!is.null(iati_identifier_ops)) {
    thisiati_identifier_ops <- iati_identifier_ops
    thisyear <-  year
    df <- df |> 
      dplyr::filter(iati_identifier_ops == thisiati_identifier_ops &
            year == thisyear )
  } else if (!is.null(ctr_name)) {
    thisctr_name <- ctr_name
    thisyear <-  year
    df <- df |> 
      dplyr::filter( ctr_name == thisctr_name &
            year == thisyear )
  }
  
  df2 <- df    |>
    dplyr::select(participating_org_eng, 
                  participating_org_type_name, 
                  participating_org_role_name) |>
     tidyr::pivot_wider(names_from = participating_org_role_name, 
              values_from = participating_org_eng ,
              values_fn = list) |>
    dplyr::select( - Accountable)  |>
    dplyr::rename(Organisation =participating_org_type_name) 
  ## replace null values...
  df2[df2 == 'NULL'] <- as.list(" ")
  
  
  df3 <- df    |>
    dplyr::select(participating_org_eng, 
                  participating_org_type_name, 
                  participating_org_role_name) |>
    #  count(across(everything())) |>
     tidyr::pivot_wider(names_from = participating_org_role_name, 
               values_from = participating_org_eng,
                values_fn = function(x) length(!is.na(x)),
                values_fill = 0)
  
  ##df |> dplyr::select(participating_org_type, participating_org_role ) |> dplyr::distinct()
   
  ## Let's build a table with a participating type as row - role as column -
  # and in the cell the numeber and list of corresponding org.. participating_org_eng
  ## Facet this by year... 
  
  # Dummy data
    # participating_org_type_name <- LETTERS[1:8]
    # participating_org_type_role <- paste0("var", seq(1,4))
    # df <- expand.grid(participating_org_type_name = participating_org_type_name,
    #                   participating_org_type_role = participating_org_type_role)
    # df$count <- runif(32, 0, 5)
  
  
#  p <- df3 |> 
# #  dplyr::filter(transaction_value_USD  <= 1000000 & transaction_value_USD  > 1000) |> 
#   ggplot2::ggplot(ggplot2::aes(x =  participating_org_type_name, 
#                                y = participating_org_type_role , 
#                                fill = count,
#                                label = count)) +
#     
#   ggplot2::geom_tile(alpha = 0.9) +  
#   ggplot2::geom_text( size=2.5)  + 
#   #ggplot2::scale_fill_viridis_c(option = "inferno", na.value = "grey50" ) +
#   ggplot2::scale_fill_gradient2(low = "white" ,
#                        mid = "#FFFFCC",
#                        high = "#075AFF") 
#   unhcrthemes::theme_unhcr(grid =  FALSE, axis = FALSE, axis_title =  TRUE, legend = FALSE)+
#   ggplot2::labs(
#     title = paste0(" Partners"),
#     subtitle = paste0("In ", programme_lab, " recorded since ", year,""),
#     x = "Organisation Type",
#     y = "Organisation Role",
#     caption = "Source: Data published by UNHCR as part of the International Aid Transparency Initiative (IATI)" ) 
 
  p <- knitr::kable( df2  )
  
  return(p)
}
