# Generated by fusen: do not edit by hand

#' show_implementers Title
#' @param year year to select starting from 2016 - could be one year or a list
#' @param geo Region or Country or Site
#' @param sector Sectors
#' @param metric Metrics could be USD or Number of project
#' 
#' @inheritParams ggplot2::ggplot
#' @return 1
#' @export
#'
#' @examples
#' show_implementers()
show_implementers <- function(year, geo, sector, metric) {
  1
}
