# WARNING - Generated by {fusen} from dev/dev_unhcr_programme.Rmd: do not edit by hand


# usethis::use_rmarkdown_template(
#   template_name = "iati_compare",
#   template_dir = NULL,
#   template_description = "Compare",
#   template_create_dir = TRUE
# )


#' Generate a summary powerpoint
#' 
#' @param year A numeric value or a vector of numeric value to filter on year. Note that data pre-2022 are using a different set of indicators
#' @param ctr_name A character vector corresponding to the name of the country.
#' @param folder folder within your project where to put the generated report. 
#'              Folder will be created if it does not exist
#' 
#' @importFrom unhcrdown pptx_slides
#' @importFrom dplyr filter select pull
#' @importFrom rmarkdown render
#' @importFrom here here
#' @importFrom countrycode countrycode
#' @importFrom stringr str_replace_all
#' 
#' @return nothing the file for the report is generated
#' 
#' @export 
#'
#' @examples
#' # iati::template_compare(year = 2022, folder = "dev/Result")
template_compare <- function(year = 2022,
                          folder = "Compare") {
  
  ## Create the outfolder if it does not exist
  output_dir <- paste0(getwd(),"/",folder)
  if (!dir.exists(output_dir)) {dir.create(output_dir)}
  
  rmarkdown::render(
    system.file("rmarkdown/templates/iati_compare/skeleton/skeleton.Rmd", package = "iati"),
    output_file = here::here(folder, paste0('Result_Resource',
                                            '-', year, '.pptx') ),
    params = list(year = year)  )
}
