# WARNING - Generated by {fusen} from dev/dev_unhcr_programme.Rmd: do not edit by hand


# usethis::use_rmarkdown_template(
#   template_name = "iati_prez",
#   template_dir = NULL,
#   template_description = "UNHCR IATI",
#   template_create_dir = TRUE
# )


#' Generate a summary powerpoint
#' 
#' @param year A numeric value or a vector of numeric value to filter on year. Note that data pre-2022 are using a different set of indicators
#' @param ctr_name A character vector corresponding to the name of the country.
#' @param folder folder within your project where to put the generated report. 
#'              Folder will be created if it does not exist
#' 
#' @importFrom unhcrdown pptx_slides
#' @importFrom dplyr filter select pull
#' @importFrom rmarkdown render
#' @importFrom here here
#' @importFrom countrycode countrycode
#' @importFrom stringr str_replace_all
#' 
#' @return nothing the file for the report is generated
#' 
#' @export 
#'
#' @examples
#'
#' ## generate for one country
#' # iati::template_prez(year = 2022, 
#' #                     ctr_name = "Brazil",
#' #                     folder = "dev/Prez")
#'
#' # ## Generate for all operation specific region
#' # reg <- iati::dataActivity |>
#' #   dplyr::select( unhcr_region) |>
#' #   dplyr::filter(! is.na(unhcr_region)) |>
#' #   dplyr::distinct() |>
#' #   dplyr::pull() 
#' # 
#' # thisfolder <- "dev/SMR" 
#' # 
#' # for (region in reg) { 
#' #       cat(paste0( region,   "\n"))
#' #
#' #       # region <- "The Americas"   
#' #       countries <- iati::dataActivity |>
#' #         dplyr::filter( unhcr_region ==  region) |>
#' #         dplyr::select(ctr_name) |>
#' #         dplyr::distinct() |>
#' #         dplyr::pull() 
#' #       
#' #       for ( ctr in countries) {
#' #         cat(paste0("Generating for ", ctr, "\n"))
#' #         iati::template_prez(year = 2022,
#' #                             ctr_name = ctr,
#' #                             folder =  thisfolder)  
#' #         }
#' #     }
template_prez <- function(year = 2022,
                          ctr_name,   
                          folder = "Prez") {
  
  ## Create the outfolder if it does not exist
  output_dir <- paste0(getwd(),"/",folder)
  if (!dir.exists(output_dir)) {dir.create(output_dir)}
  
  rmarkdown::render(
    system.file("rmarkdown/templates/iati_prez/skeleton/skeleton.Rmd", package = "iati"),
    output_file = here::here(folder, paste0('Strategic_Moment_of_Reflection-',
                                            stringr::str_replace_all( 
                           countrycode::countrycode(ctr_name,
                                               origin = "country.name",
                                               destination = "unhcr.region"), " ", "_"),
                                            "__",
                                            stringr::str_replace_all( ctr_name, " ", "_"),
                        '-', year, '.pptx') ),
    params = list(ctr_name = ctr_name, 
                  year = year)  )
}
